jpush/jpush-api-java-client

src/main/java/cn/jpush/api/report/ReportClient.java

modify ReportClient change msgid from int to long

---

src/main/java/cn/jpush/api/common/resp/ResponseWrapper.java

* 修改ResponseWrapper，将内部类改为静态内部类，同时修改JsonArray时处理bug

modify ResponseWrapper fix jsonArrry bug

---

pom.xml
src/main/java/cn/jpush/api/JPushClient.java
src/main/java/cn/jpush/api/common/ClientConfig.java
src/main/java/cn/jpush/api/common/resp/ResponseWrapper.java
src/main/java/cn/jpush/api/report/MessagesResult.java
src/main/java/cn/jpush/api/schedule/ScheduleClient.java
src/main/java/cn/jpush/api/schedule/ScheduleListResult.java
src/main/java/cn/jpush/api/schedule/ScheduleResult.java
src/main/java/cn/jpush/api/schedule/model/IModel.java
src/main/java/cn/jpush/api/schedule/model/SchedulePayload.java
src/main/java/cn/jpush/api/schedule/model/TriggerPayload.java
src/main/java/cn/jpush/api/schedule/package-info.java
src/main/java/cn/jpush/api/utils/TimeUtils.java
src/test/java/cn/jpush/api/BaseTest.java
src/test/java/cn/jpush/api/schedule/ScheduleClientTest.java
src/test/java/cn/jpush/api/schedule/model/TriggerPayloadTest.java

* MessagesResult 增加了自定义消息点击结果，iOS自定义消息结果
* ResponseWrapper 删除无用引用

modify MessagesResult add custom click

---

src/main/java/cn/jpush/api/JPushClient.java

add getScheduleList fun

---

example/main/java/cn/jpush/api/examples/ScheduleExample.java
src/main/java/cn/jpush/api/JPushClient.java
src/main/java/cn/jpush/api/common/Week.java
src/main/java/cn/jpush/api/schedule/model/TriggerPayload.java

add schedule update apis

---

README.md

modify Readme.md file

---

README.md

modify server doc url

---

src/main/java/cn/jpush/api/report/MessagesResult.java
src/main/java/cn/jpush/api/report/ReceivedsResult.java

* 送达统计查询接口增加iOS自定义消息
* 消息统计接口增加WinPhone的结果

add ios msg received

---

src/main/java/cn/jpush/api/common/connection/NativeHttpClient.java

modify tls version

---

src/main/java/cn/jpush/api/push/model/SMS.java

fix SMS methond bug

---

README.md
pom.xml

modify readme

---

example/main/java/cn/jpush/api/examples/DevcieExample.java
src/main/java/cn/jpush/api/JPushClient.java
src/main/java/cn/jpush/api/common/ClientConfig.java
src/main/java/cn/jpush/api/common/connection/NativeHttpClient.java
src/main/java/cn/jpush/api/device/DeviceClient.java
src/main/java/cn/jpush/api/push/PushClient.java
src/main/java/cn/jpush/api/report/ReportClient.java
src/main/java/cn/jpush/api/schedule/ScheduleClient.java

* 支持SSL version可配置
* 支持Read Timeout可配置
* 支持Connection Timeout可配置

add ssl version to ClientConfig

---

README.md
example/main/java/cn/jpush/api/examples/DeviceExample.java

* 修改device example名称
* 修改README文件

fix device example name

---

pom.xml
src/main/java/cn/jpush/api/JPushClient.java

fix jpush client bug

---

src/main/java/cn/jpush/api/device/DeviceClient.java
src/main/java/cn/jpush/api/report/ReceivedsResult.java

* 修改bind mobile为空异常的bug
* 修改received 结果字段错误bug

fix device and receved bug

---

src/main/java/cn/jpush/api/JPushClient.java
src/main/java/cn/jpush/api/device/DeviceClient.java

fix comment

---

src/main/java/cn/jpush/api/JPushClient.java
src/main/java/cn/jpush/api/device/DeviceClient.java
src/main/java/cn/jpush/api/report/ReceivedsResult.java

merge version 3.2.9

---

src/main/java/cn/jpush/api/push/model/PushPayload.java
src/test/java/cn/jpush/api/push/model/PushPayloadTest.java

修改Android平台Notification+Message长度限制为4000字节

Android平台Notification+Message长度限制修改

---

example/main/java/cn/jpush/api/examples/PushExample.java

modify push example add build extra example

---

.classpath
.gitignore
.project
README.md
example/main/java/cn/jpush/api/examples/PushExample.java
example/main/java/cn/jpush/api/examples/ReportsExample.java
pom.xml
src/main/java/cn/jpush/api/push/model/Message.java
src/main/java/cn/jpush/api/push/model/PushPayload.java
src/main/java/cn/jpush/api/push/model/SMS.java
src/main/java/cn/jpush/api/report/ReportClient.java

3.3.6 master

---

pom.xml
src/main/java/cn/jpush/api/JPushClient.java
src/main/java/cn/jpush/api/device/DeviceClient.java
src/test/java/cn/jpush/api/device/DeviceNormalRemoteTest.java

新增JPushClient#removeDevicesFromAlias方法

支持解绑设备与别名的绑定关系

---

pom.xml

jiguang-common -> 1.1.9

---

README.md

更新文档中的依赖版本:
jiguang-common -> 1.1.10
jpush-client -> 3.4.8

Upgrade DOC
